# Taken from https://github.com/facebookresearch/moco/blob/main/detection/configs/Base-RCNN-C4-BN.yaml
# Changes: use BN instead of SyncBN for MODEL.RESNET.NORM as we're running on a single gpu. 
#          Also, smaller SOLVER.IMS_PER_BATCH due to memory constraints
MODEL:
  META_ARCHITECTURE: "GeneralizedRCNN"
  RPN:
    PRE_NMS_TOPK_TEST: 6000
    POST_NMS_TOPK_TEST: 1000
  ROI_HEADS:
    NAME: "Res5ROIHeadsExtraNorm"
  BACKBONE:
    FREEZE_AT: 0
  RESNETS:
    NORM: "BN"
TEST:
  PRECISE_BN:
    ENABLED: True
SOLVER:
  IMS_PER_BATCH: 1
  BASE_LR: 0.02
